export const RETENTION_HOT_RAW_HOURS = 48
export const RETENTION_COLLECTOR_RUNS_DAYS = 14
export const RETENTION_HISTORY_5M_DAYS = 30
export const RETENTION_HISTORY_10M_DAYS = 90
export const RETENTION_DAILY_SUMMARY_DAYS = 365
