name = "livefield-kick-collector"
main = "src/index.ts"
compatibility_date = "2026-03-01"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "livefield"
database_id = "e1bb4736-b7ad-4194-9ed4-8444479794b6"
